openapi: 3.0.0
info:
  title: ' family album'
  version: 1.0.0
paths:
  /files:
    get:
      summary: getFiles
      operationId: getFiles
      parameters:
        -
          name: date
          in: query
          schema:
            type: integer
        -
          name: start
          in: query
          schema:
            type: integer
      responses:
        '200':
          description: ok
        '400':
          description: 'Bad Request'
        '403':
          description: Forbidden
    delete:
      summary: deleteFile
      operationId: deleteFile
      parameters:
        -
          name: fileId
          in: query
          schema:
            type: integer
      responses:
        '200':
          description: ok
        '403':
          description: Forbidden
        '400':
          description: 'Bad Request'
  /login:
    post:
      summary: login
      operationId: login
      parameters:
        -
          name: login
          in: query
          schema:
            type: string
        -
          name: password
          in: query
          schema:
            type: string
      responses:
        '200':
          description: ok
        '403':
          description: Forbidden
        '400':
          description: 'Bad Request'
        '404':
          description: 'user not found'
  reg:
    post:
      summary: reg
      operationId: reg
      parameters:
        -
          name: login
          in: query
          schema:
            type: string
        -
          name: password
          in: query
          schema:
            type: string
      responses:
        '200':
          description: ok
        '404':
          description: 'Not Found'
        '400':
          description: 'Bad Request'
